# Generated by Django 5.2.5 on 2025-10-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="platform",
            field=models.CharField(
                choices=[
                    ("PS1", "PlayStation 1"),
                    ("PS2", "PlayStation 2"),
                    ("PS3", "PlayStation 3"),
                    ("PS4", "PlayStation 4"),
                    ("PS5", "PlayStation 5"),
                    ("XBOX", "Xbox"),
                    ("XBOX360", "Xbox 360"),
                    ("XBOXONE", "Xbox One"),
                    ("XBOXSERIES", "Xbox Series X/S"),
                    ("SWITCH", "Nintendo Switch"),
                    ("PC", "PC"),
                    ("MOBILE", "Mobile"),
                ],
                default="PC",
                max_length=20,
            ),
        ),
    ]
